version: '3.4'

services:
  usertaskjwt.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9900
      - ASPNETCORE_HTTPS_PORTS=9901
    ports:
      - "9900:9900"
      - "9901:9901"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro